language: node_js
node_js:
- '12'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=leroymerlin)
  - secure: CQ44ZVjPAIVRvGgMcduSAX4VmaOrzF3nrJXPFUsNQ2tMVVdaAlI1zTNkdfntqigZgz6Mpk9x+2FcA8qrkNzQ4cW0lPP9f5dBtSH1xetfpXDFKprW4bqzmhgXSXJFTOYxkChOBPmCYJr+Vv4XqDkv/dBEPdfRSgvVyd5YxHSd5HBU91rKyR+Hox7LTnhmlXleLIs11EQgp7RK+L28MBCtCqAa2niFlKKRlqupm2FSpZzxCh9qeY0wKCQzPE+QZUm4waJ1SUGKQwbzAfyOxu2O6rwzaTSknfdJoSX6AMxjRTWBC9c3VfUGM3wjVJIqMhiUj2FQhVIjiDyX/W60/q3UMC5WYzSvEDDfhnKCPwiUKSU7HvSxx9q2YP34evxKo7KPahz9zLlQZvW+GBMyI9hbMDBTALuQVVzhftsvqfrogyYhkEPviiYiVADWNxhacsbUjRA5svXnZvtmCPo7fLFwel/krgC5Z8AwAY0YxWjSHNVScUkieSDCrlxrC09vTtG60unt9gtXbD5ruUkDLWSUwHBv2p0WY1TdP+2Vlf3yYfBvEVbqi59AxG+T17bq7Xv3QZnkrwC+UOCNCeg+gHPv+fRpUaYWzCO4uaoY/nlJa7RulQFhGca3A//6xRo/KgWw9JJnOXJelNjE9oHCUu9xShotUZKOF+O93V/BRqs9ITo=
  # MATTERMOST_HOOK_URL
  - secure: qYHpa4B1SwtomMhNSpBeEqpc5HMHYFIbI71zvX5K+sIYDqCvJQzRQ+uRsv2EfPqvvdEiSstkqcHB5sDk0xSRnlbEho7UCgZNMHu8aq93L4G59VxYmxPaHb9m+TdkZXed9tdkWoWRQr/HGmA6xF7T2oLVkK9eRW70be+cbqQsGJfzI1XbAeH/OulH+FR7U9rkCVLj5W+eUJcYLgNvYgMd2ntZqBr1fwmQgCBJ/ILGVEtP/bpywYChymcBHRoV/6DlcmA+r0KFQtHesP1PohA7VzoypYsIv9iwhwDG3xIJjoqUl8P8eSBLZ59ukMbj4imDl3op904o4xxCB6MvcRLJTrvfzDQawb4/UyrEEbGo6a2YF++yC/NQdI758cB/UbOJIBgqwBviNWpRM2RDlNDcpZDBv/nGAt9O1CnhfzO9+9JLWw5oMfVc2nu9w9/nJCqL9dAD7ofZLS6XPN2uEzfD8QF+uoU6sqgxwmRqY72BK+wyOqdgSTfEM0oaAAgGqFumMGTuRJfES9UphOGpoA/aZfxOwQbBwaeltqH+aBhFhEtGSHbeatBXAVcOY/g8H9be7Z9fdljAbSuSRtivSxQVIbGL8I2vOwSrgIdSkiRxVEzwoj/JS9/Y+hTCN7HGIvJf8vEDSFUytPfmSEDCnC28v5j5fCvMXH1rSzfgeyEebGo=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
